name: light_html_editor
description: A lightweight HTML editor for Flutter. Provides functionality to edit and parse simple HTML code.
version: 0.0.15
homepage: "https://manuelh.at/"
repository: https://github.com/herrytco/Flutter-HTML-Editor

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.0.10

  # Need 3.0.0 because of flutter_svg dependency
  flutter_html: ^3.0.0-alpha.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/icons/editor/italics.png
    - assets/icons/editor/underline.png
    - assets/icons/editor/bold.png
